services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=yoruwear
      - MYSQL_USER=yoruwear_user
      - MYSQL_PASSWORD=yourpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev # Now points to development Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://yoruwear_user:yourpassword@mysql:3306/yoruwear
    volumes:
      - ./server/src:/app/src # Mount source for hot reload
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:3000/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  client:
    build:
      context: ./client
      dockerfile: Dockerfile # Now points to development Dockerfile
    ports:
      - "4200:4200" # Development port
    environment:
      - NODE_ENV=development
    volumes:
      - ./client/src:/app/src # Mount source for hot reload
      - ./client/public:/app/public
      - /app/node_modules # Anonymous volume to preserve node_modules
    depends_on:
      server:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:80/" ]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  mysql_data:
