version: '3.8'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    healthcheck:
      # give the server a little more time to boot and respond
      test: ["CMD", "curl", "-f", "http://127.0.0.1:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      server:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80/" ]
      interval: 30s
      timeout: 5s
      retries: 3
