services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=yoruwear
      - MYSQL_USER=yoruwear_user
      - MYSQL_PASSWORD=yourpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Development server with hot reload
  server-dev:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - BUN_ENV=development
      - DATABASE_URL=mysql://yoruwear_user:yourpassword@mysql:3306/yoruwear
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      # Mount source code for hot reload
      - ./server/src:/app/src
      - ./server/package.json:/app/package.json
      - ./server/bun.lock:/app/bun.lock
      - ./server/tsconfig.json:/app/tsconfig.json
    develop:
      watch:
        - action: sync
          path: ./server/src
          target: /app/src
        - action: rebuild
          path: ./server/package.json

  # Development client with hot reload
  client-dev:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
    depends_on:
      - server-dev
    volumes:
      # Mount source code for hot reload
      - ./client/src:/app/src
      - ./client/angular.json:/app/angular.json
      - ./client/tsconfig.json:/app/tsconfig.json
      - ./client/tsconfig.app.json:/app/tsconfig.app.json
      - ./client/package.json:/app/package.json
      - ./client/package-lock.json:/app/package-lock.json
    develop:
      watch:
        - action: sync
          path: ./client/src
          target: /app/src
        - action: sync
          path: ./client/angular.json
          target: /app/angular.json
        - action: rebuild
          path: ./client/package.json

volumes:
  mysql_data:
