version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=yoruwear
      - MYSQL_USER=yoruwear_user
      - MYSQL_PASSWORD=yourpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql://yoruwear_user:yourpassword@mysql:3306/yoruwear
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      # give the server a little more time to boot and respond
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:3000/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      server:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:80/" ]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  mysql_data:
