[phases.setup]
nixPkgs = ["bun", "nodejs"]

[phases.install]
cmds = ["bun install --frozen-lockfile"]

[phases.build]
cmds = [
  "bun run build"
]

[start]
cmd = "bun src/index.ts"

[variables]
NODE_ENV = "production"
BUN_ENV = "production"